# -*- coding: utf-8 -*-
"""Multivariate Quantum Eigenvalue Transformation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rF5sYCwb78zPK0Udqhciwgwqfctmz1-y

Installation
"""
"""Imports"""

from numpy.polynomial import Chebyshev
from numpy.polynomial.chebyshev import cheb2poly
from numpy.polynomial import Polynomial
import qualtran
import sympy as sp
import scipy
from qualtran import *
import qualtran
from qualtran import *
from qualtran.bloqs import *
import math
import numpy as np
from qualtran.bloqs.block_encoding import ChebyshevPolynomial
from qualtran import Bloq, BloqBuilder, QUInt, QAny
from qualtran.bloqs.data_loading.qrom import QROM
from qualtran.bloqs.arithmetic.permutation import Permutation
from qualtran.bloqs.basic_gates import Swap
from qualtran.bloqs.block_encoding import BlockEncoding, Unitary
from qualtran.bloqs.basic_gates import XGate, ZGate, Identity
from qualtran import Bloq, CompositeBloq, BloqBuilder, Signature, Register
from qualtran import QBit, QInt, QUInt, QAny
from qualtran.drawing import show_bloq, show_call_graph, show_counts_sigma
from typing import *
from qualtran.bloqs.arithmetic import *
import numpy as np
import sympy
from qualtran.bloqs.block_encoding import LinearCombination
import cirq
from qualtran.bloqs.block_encoding import Product as BlockEncodingProduct
from qualtran.bloqs.reflections.prepare_identity import PrepareIdentity
from qualtran.bloqs.state_preparation.black_box_prepare import BlackBoxPrepare
from qualtran import cirq_interop
from qualtran.bloqs.block_encoding import TensorProduct
import qualtran.simulation as sim
from qualtran.bloqs.qsp.generalized_qsp import GeneralizedQSP
from itertools import product
from numpy.polynomial import Chebyshev
from functools import partial

"""Q_s Helper"""

def generate_q_s(r, g, s, prod, variables):
  overall = 1
  bounds = [(variables[i],-1,1) for i in range(r)]
  integral = sympy.integrate(prod,*bounds)
  for k in range(r):
      delta = 1 if s[k] == 0 else 0
      coef = (2 - delta)/sp.pi
      overall = overall*coef
  return overall*integral

"""Infinity Norm Finder"""

def infinity_norm(p, range):
  roots = p.deriv().roots()
  return max([sp.Abs(p(root)) for root in roots if range[0] <= root and root <= range[1]] + [sp.Abs(p(range[0]))]+[sp.Abs(p(range[1]))])

"""Core MQET"""
    
# Assues g is a sympy polynomial
def MQET(commuting_operators, D, r, g, vars):
  g = sp.Poly(g.as_expr().subs({
      g.gens[i]: 
          commuting_operators[i].alpha * g.gens[i]
      for i in range(r+1)             
      }, simultaneous = True), *g.gens)
  u_s_a_list = []
  B = []
  for s in product(range(D),repeat = r):
    p_s = []
    div_functions = []
    for s_k in s:
      p_s.append(Chebyshev.basis(s_k))
    integrand_functions = [g.as_expr()]+[sp.chebyshevt(s[i],vars[i])/sp.sqrt(1-vars[i]**2) for i in range(r)]
    prod = 1
    for func in integrand_functions:
      prod = prod * func
    q_s = sp.Poly(generate_q_s(r,g,s,prod, vars),vars[-1])
    coeffs = np.array(q_s.all_coeffs(),dtype = np.float64)[::-1]
    q_s = Polynomial(coeffs).convert(kind = Chebyshev)
    # Make B_s
    B_s = infinity_norm(q_s, [-1,1])
    for k in range(len(p_s)):
        B_s = B_s * np.real_if_close(infinity_norm(p_s[k], [-1,1]))
    # Q_s block encoding
    encodings = []
    if np.isclose(np.real_if_close(infinity_norm(q_s, [-1,1])),0):
        continue
    B.append(np.real_if_close(B_s))
    q_s_hat = q_s/infinity_norm(q_s, [-1,1])
    q_s_hat_bes = []
    q_s_hat_coefficients = []
    for i in range(len(q_s_hat.coef)):
      if q_s_hat.coef[i] != 0:
        q_s_hat_bes.append(ChebyshevPolynomial(commuting_operators[r], order=i))
        q_s_hat_coefficients.append(np.real_if_close(q_s_hat.coef[i]))
    if len(q_s_hat_bes) ==  1:
        encodings.append(q_s_hat_bes[0])
    else:
        encodings.append(LinearCombination(block_encodings = tuple(q_s_hat_bes),lambd = tuple(q_s_hat_coefficients), lambd_bits = 1))
    # P_s_k_hat operators
    for k in range(len(s)):
      encodings.append(ChebyshevPolynomial(commuting_operators[k], order=s[k]))
    u_s_a_list.append(BlockEncodingProduct(tuple(encodings)))
  if len(B) == 1:
      return LinearCombination(block_encodings = (u_s_a_list[0],u_s_a_list[0]), lambd = (B[0]/2,B[0]/2) ,lambd_bits = 1)
      
  return LinearCombination(block_encodings = tuple(u_s_a_list), lambd = tuple(B), lambd_bits = 1)

"""testing

x = sp.symbols("x")
q_s = sp.Poly(5*x,x)
coeffs = np.array(q_s.all_coeffs(),dtype = complex)[::-1]
q_s = Polynomial(coeffs).convert(kind = Chebyshev)
print(infinity_norm(q_s,range = [-1,1]))
print(q_s.coef[1])
# implementing tests
"""
