# -*- coding: utf-8 -*-
"""QuFEM_in_Qualtran.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d1-BRF9ILXUjYE62_qy0TQEfmZxzWQa3

Imports
"""

from itertools import product as cartproduct
import math
import random
from typing import *
import qu_fem_in_qualtran
from qu_fem_in_qualtran.mqet import MQET
from qu_fem_in_qualtran.quantum_linear_systems import qlsp_solver_prepared
from qu_fem_in_qualtran.quantum_linear_systems import prep_vector
from qualtran.bloqs.mod_arithmetic import *
import cirq
import numpy as np
import pennylane as qml
import pyqsp
import qualtran
import qualtran.simulation as sim
import sympy
from numpy.polynomial import Chebyshev
from qualtran.bloqs.bookkeeping import Partition
from scipy.linalg import sqrtm
import cmath
from qualtran import (
    Bloq,
    BloqBuilder,
    CompositeBloq,
    CtrlSpec,
    QAny,
    QBit,
    QInt,
    QUInt,
    Register,
    Signature,
    cirq_interop,
)
from qualtran import BQUInt
from sympy import legendre
from qualtran.bloqs import *
from qualtran.bloqs.arithmetic import *
from qualtran.bloqs.arithmetic.permutation import Permutation
from qualtran.bloqs.basic_gates import (
    CNOT,
    GlobalPhase,
    Hadamard,
    IntEffect,
    OneEffect,
    OneState,
    PlusState,
    Rz,
    SGate,
    Swap,
    TGate,
    XGate,
    ZeroState,
    ZGate,
)
from qualtran.bloqs.mod_arithmetic import CModMulK
from qualtran.bloqs.basic_gates import Identity
from qualtran.bloqs.block_encoding import (
    BlockEncoding,
    LinearCombination,
    Product as BlockEncodingProduct,
    TensorProduct,
    Unitary,
)
from qualtran.bloqs.data_loading.qrom import QROM
from qualtran.bloqs.qsp.generalized_qsp import GeneralizedQSP
from qualtran.bloqs.reflections.prepare_identity import PrepareIdentity
from qualtran.bloqs.rotations.phase_gradient import PhaseGradientState
from qualtran.bloqs.state_preparation.black_box_prepare import BlackBoxPrepare
from qualtran.bloqs.state_preparation.state_preparation_via_rotation import (
    StatePreparationViaRotations,
)
from itertools import combinations
from qualtran.cirq_interop import CirqGateAsBloq
from qualtran.drawing import (
    show_bloq,
    show_call_graph,
    show_counts_sigma,
)
from qualtran.bloqs.state_preparation import PrepareUniformSuperposition
from sympy import diff
import sympy as sp
from sympy import degree
from qualtran.bloqs.arithmetic import EqualsAConstant

"""Adjoint BE Wrapper"""

class AdjointBlockEncoding(BlockEncoding):
  def __init__(self,block_encoding):
    self.block_encoding = block_encoding
  @property
  def signature(self):
    return self.block_encoding.signature
  @property
  def alpha(self):
    return self.block_encoding.alpha
  @property
  def ancilla_bitsize(self):
    return self.block_encoding.ancilla_bitsize
  @property
  def epsilon(self):
    return self.block_encoding.epsilon
  @property
  def resource_bitsize(self):
    return self.block_encoding.resource_bitsize
  @property
  def signal_state(self):
    return self.block_encoding.signal_state
  @property
  def system_bitsize(self):
    return self.block_encoding.system_bitsize
  def build_composite_bloq(self, bb, system, ancilla):
    system, ancilla = bb.add(self.block_encoding.adjoint(),system = system, ancilla = ancilla)
    return {"system": system, "ancilla": ancilla}

class UniformLCU(BlockEncoding):
  def __init__(self, block_encodings):
    self.unif = PrepareUniformSuperposition(n = len(block_encodings))
    self.block_encodings = block_encodings
  @property
  def signature(self):
    return Signature([Register("system", QAny(self.system_bitsize)), Register("ancilla", QAny(self.ancilla_bitsize)),
                      Register("resource", QAny(self.resource_bitsize))])
  @property
  def alpha(self):
    return sum([block_encoding.alpha for block_encoding in self.block_encodings])
  @property
  def ancilla_bitsize(self):
    self.extra_bitsize = math.ceil(math.log(len(self.block_encodings), 2))
    ancilla_bitsize = self.extra_bitsize + max([block_encoding.ancilla_bitsize for block_encoding in self.block_encodings])
    return ancilla_bitsize
  @property
  def epsilon(self):
    return sum([block_encoding.epsilon for block_encoding in self.block_encodings])
  @property
  def resource_bitsize(self):
    return max([block_encoding.resource_bitsize for block_encoding in self.block_encodings])
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([self.ancilla_bitsize]))
  @property
  def system_bitsize(self):
    return self.block_encodings[0].system_bitsize

  def build_composite_bloq(self, bb, *, system, ancilla, resource):
    ancilla_bits = bb.split(ancilla)
    # Allocating and Setting up registers
    control = bb.join(ancilla_bits[0:self.extra_bitsize])
    rest_ancilla = bb.join(ancilla_bits[self.extra_bitsize:])
    control = bb.add(self.unif, target = control)
    # Main LCU loop
    for index in range(len(self.block_encodings)):
      block_encoding = self.block_encodings[index]
      controlled_be = block_encoding.controlled(CtrlSpec(cvs = index, qdtypes = QAny(self.extra_bitsize)))
      print(controlled_be.signature)
      rest_ancilla_bits = bb.split(rest_ancilla)
      resource_bits = bb.split(resource)
      # splitting to used portions
      if block_encoding.resource_bitsize > 0:
        used_resource = bb.join(resource_bits[0:block_encoding.resource_bitsize])
      else:
        used_resource = bb.join(resource_bits)

      if block_encoding.ancilla_bitsize > 0:
        used_ancilla = bb.join(rest_ancilla_bits[0:block_encoding.ancilla_bitsize])
      else:
        used_ancilla = bb.join(rest_ancilla_bits)
      # applying operation
      if block_encoding.ancilla_bitsize == 0 and block_encoding.resource_bitsize == 0:
        control, system = bb.add(controlled_be, ctrl = control, system = system)
      elif block_encoding.ancilla_bitsize == 0:
        control, system, used_resource = bb.add(controlled_be, ctrl = control, system = system, resource = used_resource)
      elif block_encoding.resource_bitsize == 0:
        control, system, used_ancilla = bb.add(controlled_be, ctrl = control, system = system, ancilla = used_ancilla)
      else:
        control, system, used_ancilla, used_resource = bb.add(controlled_be, ctrl = control, system = system, ancilla = used_ancilla, resource = used_resource)
      # re-splitting
      used_ancilla_bits = bb.split(used_ancilla)
      used_resource_bits = bb.split(used_resource)
      # rejoining
      if block_encoding.ancilla_bitsize > 0:
        rest_ancilla = bb.join(np.concatenate([used_ancilla_bits, rest_ancilla_bits[block_encoding.ancilla_bitsize:]]))
      else:
        rest_ancilla = bb.join(used_ancilla_bits)

      if block_encoding.resource_bitsize > 0:
        resource = bb.join(np.concatenate([used_resource_bits, resource_bits[block_encoding.resource_bitsize:]]))
      else:
        resource = bb.join(used_resource_bits)
    control = bb.add(self.unif.adjoint(), target = control)
    # rejoining and returning
    control_bits = bb.split(control)
    rest_ancilla_bits = bb.split(rest_ancilla)
    ancilla = bb.join(np.concatenate([control_bits, rest_ancilla_bits]))
    return {"system": system, "ancilla": ancilla, "resource": resource}

"""Position Operators/Q"""

class z_i(Bloq):
  def __init__(self, n, i):
    self.n = n
    self.i = i
  @property
  def signature(self):
    return Signature([Register("point",QAny(self.n))])
  def build_composite_bloq(self, bb, *, point):
    point_array = bb.split(point)
    point_array[self.n - self.i -1] = bb.add(ZGate(),q = point_array[self. n - self.i -1])
    point = bb.join(point_array, dtype = QAny(self.n))
    return {"point": point}

def build_x(n):
  N = 2**n
  coeffs = [(N-1)/2]
  unitaries = [Unitary(Identity(n))]
  for i in range(n):
    coeffs.append(-(0.5 * (2**i)))
    unitaries.append(Unitary(z_i(n,i)))
  return LinearCombination(tuple(unitaries),lambd = tuple(coeffs), lambd_bits = 1)

"""Mesh Connectivity Block Encoding"""

class o_l_numel(Bloq):
  def __init__(self, numel, numel_bits):
    self.numel = numel
    self.numel_bits = numel_bits
  @property
  def signature(self):
    return Signature([Register("el", QUInt(self.numel_bits)),Register("flag", QBit())])
  def build_composite_bloq(self, bb, *, el, flag):
    numel_reg = bb.allocate(dtype = QUInt(self.numel_bits))
    numel_reg_bits = bb.split(numel_reg)
    for index in range(self.numel_bits):
      if (self.numel >> index) & 1:
        numel_reg_bits[self.numel_bits - index - 1] = bb.add(XGate(), q = numel_reg_bits[self.numel_bits - index - 1])
    numel_reg = bb.join(numel_reg_bits, dtype = QUInt(self.numel_bits))
    numel_reg, el , flag = bb.add(GreaterThan(a_bitsize = self.numel_bits, b_bitsize = self.numel_bits), a = numel_reg, b = el, target = flag)
    numel_reg_bits = bb.split(numel_reg)
    for index in range(self.numel_bits):
      if (self.numel >> index) & 1:
        numel_reg_bits[self.numel_bits - index - 1] = bb.add(XGate(), q = numel_reg_bits[self.numel_bits - index - 1])
    numel_reg = bb.join(numel_reg_bits)
    bb.free(numel_reg)
    return {"el": el, "flag": flag}

class O_IX_1D(Bloq):
  def __init__(self, numnp_bits_1D, nen, numel, j):
    self.nen = nen
    self.numnp_bits_1D = numnp_bits_1D
    self.j = j
    self.numel = numel

  @property
  def signature(self):
    return Signature([Register("system", QAny(self.numnp_bits_1D))])
  def build_composite_bloq(self, bb, *, system):
    # Creatring j
    j_reg = bb.allocate(self.numnp_bits_1D+1)
    j_reg_bits = bb.split(j_reg)
    for index in range(self.numnp_bits_1D+1):
      if (self.j >> index) & 1:
        j_reg_bits[self.numnp_bits_1D+1 - index - 1] = bb.add(XGate(), q = j_reg_bits[self.numnp_bits_1D+1 - index - 1])
    j_reg = bb.join(j_reg_bits)
    # allocating and setting control
    ctrl = bb.allocate(1)
    ctrl = bb.add(XGate(), q = ctrl)
    # Splitting and adding extra bits for modular ops
    extra_bit = bb.allocate(1)
    extra_bit_split = bb.split(extra_bit)
    system_bits = bb.split(system)
    system_extended = bb.join(np.concatenate([extra_bit_split, system_bits]))
    # Applying ops
    mul_gate = CModMulK(QUInt(self.numnp_bits_1D+1), k = self.nen - 1 , mod= 2 ** self.numnp_bits_1D)
    ctrl, system_extended = bb.add(mul_gate, ctrl = ctrl, x = system_extended)
    j_reg, system_extended = bb.add(ModAdd(bitsize = self.numnp_bits_1D+1, mod = 2**self.numnp_bits_1D), x = j_reg, y = system_extended)
    ctrl = bb.add(XGate(), q = ctrl)
    # Splitting and freeing
    system_extended_bits = bb.split(system_extended)
    extra_bit = system_extended_bits[0]
    system = bb.join(system_extended_bits[1:])
    j_reg_bits = bb.split(j_reg)
    for index in range(self.numnp_bits_1D+1):
      if (self.j >> index) & 1:
        j_reg_bits[self.numnp_bits_1D+1 - index - 1] = bb.add(XGate(), q = j_reg_bits[self.numnp_bits_1D+1 - index - 1])
    j_reg = bb.join(j_reg_bits)
    # freeing
    bb.free(extra_bit)
    bb.free(ctrl)
    bb.free(j_reg)
    return {"system": system}

class a_j_block_encoding_1D(BlockEncoding):
  def __init__(self,numnp_bits_1D, nen, numel, j):
    self.oracle_ix = O_IX_1D(numnp_bits_1D, nen, numel, j)
    self.oracle_l_numel = o_l_numel(numel, numnp_bits_1D)
    self.numnp_bits_1D = numnp_bits_1D
    self.j = j
  @property
  def signature(self):
    return Signature([Register("system", QUInt(self.numnp_bits_1D)),Register("ancilla", QAny(1))])
  @property
  def alpha(self):
    return 1
  @property
  def ancilla_bitsize(self):
    return 1
  @property
  def epsilon(self):
    return 0
  @property
  def resource_bitsize(self):
    return 0
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([1]))
  @property
  def system_bitsize(self):
    return self.numnp_bits_1D
  def build_composite_bloq(self,bb, *, system, ancilla):
    system, ancilla = bb.add(self.oracle_l_numel, el = system, flag = ancilla)
    system = bb.add(self.oracle_ix, system = system)
    ancilla = bb.add(XGate(), q= ancilla)
    return {"system": system, "ancilla": ancilla}

class a_j_be(BlockEncoding):
  def __init__(self,numnp_bits_1D, nen_1D, numel, j, d):
    self.one_dimensional_bes = [a_j_block_encoding_1D(numnp_bits_1D, nen_1D,numel, j[i]) for i in range(d)]
    self.operation = TensorProduct(block_encodings = tuple(self.one_dimensional_bes))
  @property
  def signature(self):
    return self.operation.signature
  @property
  def alpha(self):
    return self.operation.alpha
  @property
  def ancilla_bitsize(self):
    return self.operation.ancilla_bitsize
  @property
  def epsilon(self):
    return self.operation.epsilon
  @property
  def resource_bitsize(self):
    return self.operation.resource_bitsize
  @property
  def signal_state(self):
    return self.operation.signal_state
  @property
  def system_bitsize(self):
    return self.operation.system_bitsize
  def build_composite_bloq(self, bb, *, system, ancilla):
    system, ancilla = bb.add(self.operation, system = system, ancilla = ancilla)
    return {"system": system, "ancilla": ancilla}

"""Quadrature Point Position Operators"""

class log_numel_projector(BlockEncoding):
  def __init__(self, numnp_bits_1D, numel):
    self.numnp_bits_1D = numnp_bits_1D
    self.numel = numel
  @property
  def signature(self):
    return Signature([Register("system",QAny(self.numnp_bits_1D)),Register("ancilla",QBit())])
  @property
  def alpha(self):
    return 1
  @property
  def ancilla_bitsize(self):
    return 1
  @property
  def epsilon(self):
    return 0
  @property
  def resource_bitsize(self):
    return 0
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([1]))
  @property
  def system_bitsize(self):
    return self.numnp_bits_1D
  def build_composite_bloq(self,bb, *, system, ancilla):
    numel_reg = bb.allocate(dtype = QUInt(self.numnp_bits_1D))
    numel_reg_bits = bb.split(numel_reg)
    for index in range(self.numnp_bits_1D):
      if (self.numel >> index) & 1:
        numel_reg_bits[self.numnp_bits_1D - index - 1] = bb.add(XGate(), q = numel_reg_bits[self.numnp_bits_1D - index - 1])
    numel_reg = bb.join(numel_reg_bits, dtype = QUInt(self.numnp_bits_1D))
    numel_reg, system , ancilla = bb.add(GreaterThan(a_bitsize = self.numnp_bits_1D, b_bitsize = self.numnp_bits_1D), a = numel_reg, b = system, target = ancilla)
    numel_reg_bits = bb.split(numel_reg)
    for index in range(self.numnp_bits_1D):
      if (self.numel >> index) & 1:
        numel_reg_bits[self.numnp_bits_1D - index - 1] = bb.add(XGate(), q = numel_reg_bits[self.numnp_bits_1D - index - 1])
    numel_reg = bb.join(numel_reg_bits)
    ancilla = bb.add(XGate(),q = ancilla)
    bb.free(numel_reg)
    return {"system": system, "ancilla": ancilla}
def generate_x_l_i_el(x_l_i, numel, n_bits, d):
  h = 1/numel
  coeff_1 = h * (x_l_i+ 1)/2
  coeff_2 = h
  inner = LinearCombination(block_encodings = (Unitary(Identity(n_bits)), build_x(n_bits)), lambd = (coeff_1,coeff_2),lambd_bits = 1)
  return BlockEncodingProduct((log_numel_projector(n_bits,numel), inner))
# ith coordinate of the lth gauss point for a certain element varies between elements
class gauss_point_ith_coordinate(BlockEncoding):
  def __init__(self, x_l_i, numel, n_bits_1D, d, i):
    encodings = [log_numel_projector(numel = numel,numnp_bits_1D = n_bits_1D)] * d
    encodings[d - i - 1] = generate_x_l_i_el(x_l_i = x_l_i, numel = numel, n_bits = n_bits_1D, d = d)
    self.operation = TensorProduct(block_encodings = tuple(encodings))
  @property
  def signature(self):
    return self.operation.signature
  @property
  def alpha(self):
    return self.operation.alpha
  @property
  def ancilla_bitsize(self):
    return self.operation.ancilla_bitsize
  @property
  def epsilon(self):
    return self.operation.epsilon
  @property
  def resource_bitsize(self):
    return self.operation.resource_bitsize
  @property
  def signal_state(self):
    return self.operation.signal_state
  @property
  def system_bitsize(self):
    return self.operation.system_bitsize
  def build_composite_bloq(self, bb, *, system, ancilla, resource):
    system, ancilla, resource = bb.add(self.operation, system = system, ancilla = ancilla, resource = resource)
    return {"system": system, "ancilla": ancilla, "resource":resource}

"""Gauss Tuples and Quadrature Coefficients"""

def generate_gauss_tuples_plain(G, numel, d):
  one_dimensional_points = []
  x = sp.symbols("x")
  poly = sp.Poly(legendre(G,x))
  poly_deriv = diff(poly, x)
  for x_k in poly.nroots():
    one_dimensional_points.append(x_k)
  coordinates = list(cartproduct(one_dimensional_points, repeat = d))
  total_list = []
  for point in coordinates:
    weight = 1
    point_list = list(point)
    for x_k in point:
      weight = weight * 2/((1-(x_k ** 2))* ( (poly_deriv(x_k))**2))
    point_list.append(weight)
    total_list.append(tuple(point_list))
  return total_list


def generate_c_jk_array(j,k, nodal_basis_map, gauss_tuples):
  coeff_array = []
  for i in range(len(gauss_tuples)):
    point = list(gauss_tuples[i][0:len(gauss_tuples[i])-1])
    weight = gauss_tuples[i][-1]
    coeff_array.append(float(weight * nodal_basis_map[(j,k)](*point)))
  return coeff_array

def generate_c_j_array(j, nodal_functions, gauss_tuples):
  coeff_array = []
  for i in range(len(gauss_tuples)):
    point = list(gauss_tuples[i][0:len(gauss_tuples[i])-1])
    weight = gauss_tuples[i][-1]
    coeff_array.append(float(weight * nodal_functions[j](*point)))
  return coeff_array

"""Function Operator LCU"""

def generate_function_operator_lcu_diag(G, numel, numnp, numnp_bits_1D, d, j, nodal_functions, function):
  plain_tuples = generate_gauss_tuples_plain(G, numel, d)
  c_j_array = generate_c_j_array(j, nodal_functions, plain_tuples)
  function_operators = []
  for x_l in plain_tuples:
    commuting_operators = []
    for i in range(d):
      # XG,(i)ℓi
      commuting_operators.append(gauss_point_ith_coordinate(x_l[i], numel, numnp_bits_1D, d, i))
    function_operators.append(MQET(commuting_operators, 5, d-1,function, function.gens))
  return LinearCombination(block_encodings = tuple(function_operators), lambd = tuple(c_j_array), lambd_bits = 1)

def generate_function_operator_lcu_array(G, numel, numnp, numnp_bits_1D, d, j, k, nodal_basis_map, function):
  plain_tuples = generate_gauss_tuples_plain(G, numel, d)
  c_jk_array = generate_c_jk_array(j,k, nodal_basis_map, plain_tuples)
  function_operators = []
  for x_l in plain_tuples:
    commuting_operators = []
    for i in range(d):
      # XG,(i)ℓi
      commuting_operators.append(gauss_point_ith_coordinate(x_l[i], numel, numnp_bits_1D, d, i))
    function_operators.append(MQET(commuting_operators, 5, d-1,function, function.gens))
  return LinearCombination(block_encodings = tuple(function_operators), lambd = tuple(c_jk_array), lambd_bits = 1)

"""Finite Element Arrays/Vectors Assembly"""

def construct_finite_element_array(G, nen_1D, numel, numnp, numnp_bits_1D, d, nodal_basis_map, f):
  block_encodings = []
  tensored_basis = cartproduct(range(nen_1D), repeat = d)
  for j,k in cartproduct(tensored_basis, repeat = 2):
    a_j = a_j_be(numnp_bits_1D, nen_1D, numel, j, d)
    a_k_adj = AdjointBlockEncoding(a_j_be(numnp_bits_1D, nen_1D, numel, k, d))
    sum_functions = generate_function_operator_lcu_array(G, numel, numnp, numnp_bits_1D, d, j, k, nodal_basis_map, f)
    block_encodings.append(BlockEncodingProduct((a_j, sum_functions, a_k_adj)))
  return UniformLCU(block_encodings)

def construct_source_vector_diag(G, nen_1D, numel, numnp, numnp_bits_1D, d, nodal_basis_functions, source_function):
  block_encodings = []
  tensored_basis = cartproduct(range(nen_1D), repeat = d)
  for j in tensored_basis:
    a_j = a_j_be(numnp_bits_1D, nen_1D, numel, j, d)
    sum_functions = generate_function_operator_lcu_diag(G, numel, numnp, numnp_bits_1D, d, j, nodal_basis_functions, source_function)
    block_encodings.append(BlockEncodingProduct((a_j, sum_functions, AdjointBlockEncoding(a_j))))
  return UniformLCU(block_encodings)

"""Boundary Conditions Operators"""

class u_b_1d(BlockEncoding):
  def __init__(self, numnp_bits_1D):
    self.numnp_bits_1D = numnp_bits_1D
  @property
  def signature(self):
    return Signature([Register("system",QAny(self.numnp_bits_1D)),Register("ancilla",QBit())])
  @property
  def alpha(self):
    return 1
  @property
  def ancilla_bitsize(self):
    return 1
  @property
  def epsilon(self):
    return 0
  @property
  def resource_bitsize(self):
    return 0
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([1]))
  @property
  def system_bitsize(self):
    return self.numnp_bits_1D
  def build_composite_bloq(self,bb, *, system, ancilla):
    equals_zero = EqualsAConstant(bitsize = self.numnp_bits_1D, val = 0)
    equals_edge = EqualsAConstant(bitsize = self.numnp_bits_1D, val = 2 ** self.numnp_bits_1D - 1)
    system, ancilla = bb.add(equals_zero, x = system, target = ancilla)
    system, ancilla = bb.add(equals_edge, x = system, target = ancilla)
    return {"system": system, "ancilla": ancilla}

class u_b(BlockEncoding):
  def __init__(self, numnp_bits_1D, d):
    self.numnp_bits_1D = numnp_bits_1D
    self.d = d
    encodings = [u_b_1d(numnp_bits_1D) for _ in range(self.d)]
    self.operation = TensorProduct(block_encodings = tuple(encodings))
  @property
  def signature(self):
    return self.operation.signature
  @property
  def alpha(self):
    return self.operation.alpha
  @property
  def ancilla_bitsize(self):
    return self.operation.ancilla_bitsize
  @property
  def epsilon(self):
    return self.operation.epsilon
  @property
  def resource_bitsize(self):
    return self.operation.resource_bitsize
  @property
  def signal_state(self):
    return self.operation.signal_state
  @property
  def system_bitsize(self):
    return self.operation.system_bitsize
  def build_composite_bloq(self,bb, *, system, ancilla):
    system, ancilla = bb.add(self.operation, system = system, ancilla = ancilla)
    return {"system": system, "ancilla": ancilla}

"""Testing"""
