# -*- coding: utf-8 -*-
"""qu_fem

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0eBHTWviBdygcRxZH2ZWczoQ2U7DVw7

Imports
"""

from itertools import product as cartproduct
import math
import random
from typing import *
import qu_fem_in_qualtran
from qu_fem_in_qualtran.mqet import MQET
from qu_fem_in_qualtran.quantum_linear_systems import qlsp_solver_prepared
from qu_fem_in_qualtran.quantum_linear_systems import prep_vector
from qualtran.bloqs.mod_arithmetic import *
import cirq
import numpy as np
import pennylane as qml
import pyqsp
import qualtran
import qualtran.simulation as sim
import sympy
from numpy.polynomial import Chebyshev
from qualtran.bloqs.bookkeeping import Partition
from scipy.linalg import sqrtm
import cmath
from qualtran import (
    Bloq,
    BloqBuilder,
    CompositeBloq,
    CtrlSpec,
    QAny,
    QBit,
    QInt,
    QUInt,
    Register,
    Signature,
    cirq_interop,
)
from qualtran import BQUInt
from sympy import legendre
from qualtran.bloqs import *
from qualtran.bloqs.arithmetic import *
from qualtran.bloqs.arithmetic.permutation import Permutation
from qualtran.bloqs.basic_gates import (
    CNOT,
    GlobalPhase,
    Hadamard,
    IntEffect,
    OneEffect,
    OneState,
    PlusState,
    Rz,
    SGate,
    Swap,
    TGate,
    XGate,
    ZeroState,
    ZGate,
)
from qualtran.bloqs.mod_arithmetic import CModMulK
from qualtran.bloqs.basic_gates import Identity
from qualtran.bloqs.block_encoding import (
    BlockEncoding,
    LinearCombination,
    Product as BlockEncodingProduct,
    TensorProduct,
    Unitary,
)
from qualtran.bloqs.data_loading.qrom import QROM
from qualtran.bloqs.qsp.generalized_qsp import GeneralizedQSP
from qualtran.bloqs.reflections.prepare_identity import PrepareIdentity
from qualtran.bloqs.rotations.phase_gradient import PhaseGradientState
from qualtran.bloqs.state_preparation.black_box_prepare import BlackBoxPrepare
from qualtran.bloqs.state_preparation.state_preparation_via_rotation import (
    StatePreparationViaRotations,
)
from itertools import combinations
from qualtran.cirq_interop import CirqGateAsBloq
from qualtran.drawing import (
    show_bloq,
    show_call_graph,
    show_counts_sigma,
)
from qualtran.bloqs.state_preparation import PrepareUniformSuperposition
from sympy import diff
import sympy as sp
from sympy import degree
from qualtran.bloqs.arithmetic import EqualsAConstant

"""BE Wrappers"""

class AdjointBlockEncoding(BlockEncoding):
  def __init__(self,block_encoding):
    self.block_encoding = block_encoding
  @property
  def signature(self):
    return self.block_encoding.signature
  @property
  def alpha(self):
    return self.block_encoding.alpha
  @property
  def ancilla_bitsize(self):
    return self.block_encoding.ancilla_bitsize
  @property
  def epsilon(self):
    return self.block_encoding.epsilon
  @property
  def resource_bitsize(self):
    return self.block_encoding.resource_bitsize
  @property
  def signal_state(self):
    return self.block_encoding.signal_state
  @property
  def system_bitsize(self):
    return self.block_encoding.system_bitsize
  def build_composite_bloq(self, bb, **soqs):
    return bb.add_d(self.block_encoding.adjoint(),**soqs,)


"""Mesh Oracles"""

class z_i(Bloq):
  def __init__(self, n, i):
    self.n = n
    self.i = i
  @property
  def signature(self):
    return Signature([Register("point",QAny(self.n))])
  def build_composite_bloq(self, bb, *, point):
    point_array = bb.split(point)
    point_array[self.n - self.i -1] = bb.add(ZGate(),q = point_array[self. n - self.i -1])
    point = bb.join(point_array, dtype = QAny(self.n))
    return {"point": point}

def build_x(n, h, x_l_i):
  coeff_1 = h * (x_l_i+ 1)/2
  coeff_2 = h
  N = 2**n
  coeffs = [coeff_1, h * (N-1)/2]
  unitaries = [Unitary(Identity(n)),Unitary(Identity(n))]
  for i in range(n):
    coeffs.append(-(coeff_2 * 0.5 * (2**i)))
    unitaries.append(Unitary(z_i(n,i)))
  return LinearCombination(tuple(unitaries),lambd = tuple(coeffs), lambd_bits = 4)


class o_l_numel(Bloq):
  def __init__(self, numel, numel_bits):
    self.numel = numel
    self.numel_bits = numel_bits
  @property
  def signature(self):
    return Signature([Register("el", QAny(self.numel_bits)),Register("ancilla", QAny(1))])
  def build_composite_bloq(self, bb, *, el, ancilla):
    operation = LessThanConstant(bitsize = self.numel_bits, less_than_val = self.numel)
    el, ancilla = bb.add(operation, x = el, target = ancilla)
    return {"el": el, "ancilla": ancilla}

class O_IX_1D(Bloq):
  def __init__(self, numnp_bits_1D, nen, numel, j):
    self.nen = nen
    self.numnp_bits_1D = numnp_bits_1D
    self.j = j
    self.numel = numel
  @property
  def signature(self):
    return Signature([Register("system", QAny(self.numnp_bits_1D)), Register("ancilla", QAny(2))])
  def build_composite_bloq(self, bb, *, system, ancilla):
    # gate defintiions
    add_gate = AddK(dtype = QUInt(self.numnp_bits_1D), k = self.j)
    mul_gate = CModMulK(QAny(self.numnp_bits_1D+1), k = self.nen - 1 , mod= 2 ** self.numnp_bits_1D)
    # setting
    buffer, ctrl = bb.split(ancilla)
    system_bits = bb.split(system)
    system_buffered = bb.join([buffer,*system_bits])
    # Operation 1
    ctrl = bb.add(XGate(), q = ctrl)
    ctrl, system_buffered = bb.add(mul_gate, ctrl = ctrl, x = system_buffered)
    ctrl = bb.add(XGate(), q = ctrl)
    # rejoining
    system_buffered_bits = bb.split(system_buffered)
    ancilla = bb.join([ctrl,system_buffered_bits[0]])
    system = bb.join(system_buffered_bits[1:])
    # Operation 2
    system = bb.add(add_gate, x = system)
    return {"system": system, "ancilla": ancilla}

class a_j_block_encoding_1D(BlockEncoding):
  def __init__(self,numnp_bits_1D, nen, numel, j):
    self.oracle_ix = O_IX_1D(numnp_bits_1D, nen, numel, j)
    self.oracle_l_numel = o_l_numel(numel, numnp_bits_1D)
    self.numnp_bits_1D = numnp_bits_1D
    self.j = j
  @property
  def signature(self):
    return Signature([Register("system", QAny(self.numnp_bits_1D)),Register("ancilla", QAny(2))])
  @property
  def alpha(self):
    return 1
  @property
  def ancilla_bitsize(self):
    return 2
  @property
  def epsilon(self):
    return 0
  @property
  def resource_bitsize(self):
    return 0
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([2]))
  @property
  def system_bitsize(self):
    return self.numnp_bits_1D
  def build_composite_bloq(self,bb, *, system, ancilla):
    flag, rest = bb.split(ancilla)
    system, flag = bb.add(self.oracle_l_numel, el = system, ancilla = flag)
    flag = bb.add(XGate(), q = flag)
    ancilla = bb.join([rest, flag])
    system, ancilla = bb.add(self.oracle_ix, system = system, ancilla = ancilla)
    return {"system": system, "ancilla": ancilla}

class a_j_be(BlockEncoding):
  def __init__(self,numnp_bits_1D, nen_1D, numel, j, d):
    self.one_dimensional_bes = [a_j_block_encoding_1D(numnp_bits_1D, nen_1D,numel, j[i]) for i in range(d)]
    self.operation = TensorProduct(block_encodings = tuple(self.one_dimensional_bes))
  @property
  def signature(self):
    return self.operation.signature
  @property
  def alpha(self):
    return self.operation.alpha
  @property
  def ancilla_bitsize(self):
    return self.operation.ancilla_bitsize
  @property
  def epsilon(self):
    return self.operation.epsilon
  @property
  def resource_bitsize(self):
    return self.operation.resource_bitsize
  @property
  def signal_state(self):
    return self.operation.signal_state
  @property
  def system_bitsize(self):
    return self.operation.system_bitsize
  def build_composite_bloq(self, bb, *, system, ancilla):
    system, ancilla = bb.add(self.operation, system = system, ancilla = ancilla)
    return {"system": system, "ancilla": ancilla}

class unit_products(BlockEncoding):
  def __init__(self, block_encodings):
    self.block_encodings = block_encodings
    self.s_bits = max([be.system_bitsize for be in block_encodings])
    self.a_bits = max([be.ancilla_bitsize for be in block_encodings])
  @property
  def signature(self):
    return Signature([Register("system", QAny(self.s_bits)),Register("ancilla", QAny(self.a_bits))])
  @property
  def alpha(self):
    return 1
  @property
  def ancilla_bitsize(self):
    return self.a_bits
  @property
  def epsilon(self):
    return 0
  @property
  def resource_bitsize(self):
    return 0
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([self.a_bits]))
  @property
  def system_bitsize(self):
    return self.s_bits
  def build_composite_bloq(self, bb, *, system, ancilla):
    for be in self.block_encodings:
      system, ancilla = bb.add(be, system = system, ancilla = ancilla)
    return {"system": system, "ancilla": ancilla}
"""Gauss Point Operators"""

class log_numel_projector(BlockEncoding):
  def __init__(self, numnp_bits_1D, numel):
    self.numnp_bits_1D = numnp_bits_1D
    self.numel = numel
  @property
  def signature(self):
    return Signature([Register("system",QAny(self.numnp_bits_1D)),Register("ancilla",QAny(1))])
  @property
  def alpha(self):
    return 1
  @property
  def ancilla_bitsize(self):
    return 1
  @property
  def epsilon(self):
    return 0
  @property
  def resource_bitsize(self):
    return 0
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([1]))
  @property
  def system_bitsize(self):
    return self.numnp_bits_1D
  def build_composite_bloq(self,bb, *, system, ancilla):
    operation = LessThanConstant(bitsize = self.numnp_bits_1D, less_than_val = self.numel)
    system, ancilla = bb.add(operation, x = system, target = ancilla)
    ancilla = bb.add(XGate(), q = ancilla)
    return {"system": system, "ancilla": ancilla}
    
def generate_x_l_i_el(x_l_i, numel, n_bits):
  inner =  build_x(n_bits, 1/numel, x_l_i)
  return BlockEncodingProduct((log_numel_projector(n_bits,numel), inner))
# ith coordinate of the lth gauss point for a certain element varies between elements
class gauss_point_ith_coordinate(BlockEncoding):
  def __init__(self, x_l_i, numel, n_bits_1D, d, i):
    encodings = [log_numel_projector(numel = numel,numnp_bits_1D = n_bits_1D)] * d
    encodings[d - i - 1] = generate_x_l_i_el(x_l_i = x_l_i, numel = numel, n_bits = n_bits_1D)
    self.operation = TensorProduct(block_encodings = tuple(encodings))
  @property
  def signature(self):
    return self.operation.signature
  @property
  def alpha(self):
    return self.operation.alpha
  @property
  def ancilla_bitsize(self):
    return self.operation.ancilla_bitsize
  @property
  def epsilon(self):
    return self.operation.epsilon
  @property
  def resource_bitsize(self):
    return self.operation.resource_bitsize
  @property
  def signal_state(self):
    return self.operation.signal_state
  @property
  def system_bitsize(self):
    return self.operation.system_bitsize
  def build_composite_bloq(self, bb, *, system, ancilla, resource):
    system, ancilla, resource = bb.add(self.operation, system = system, ancilla = ancilla, resource = resource)
    return {"system": system, "ancilla": ancilla, "resource":resource}


def generate_gauss_tuples_plain(G, numel, d):
  one_dimensional_points = []
  x = sp.symbols("x")
  poly = sp.Poly(legendre(G,x))
  poly_deriv = diff(poly, x)
  for x_k in poly.nroots():
    one_dimensional_points.append(x_k)
  coordinates = list(cartproduct(one_dimensional_points, repeat = d))
  total_list = []
  for point in coordinates:
    weight = 1
    point_list = list(point)
    for x_k in point:
      weight = weight * 2/((1-(x_k ** 2))* ( (poly_deriv(x_k))**2))
    point_list.append(weight * ((1 / 2.0 * numel) ** d))
    total_list.append(tuple(point_list))
  return total_list


def generate_c_jk_array(j,k, nodal_basis_map, gauss_tuples):
  coeff_array = []
  for i in range(len(gauss_tuples)):
    point = [((float(x)+1.0)/2.0) for x in gauss_tuples[i][0:len(gauss_tuples[i])-1]]
    weight = gauss_tuples[i][-1]
    coeff_array.append(float(weight * nodal_basis_map[(j,k)](*point)))
  return coeff_array

def generate_c_j_array(j, nodal_functions, gauss_tuples):
  coeff_array = []
  for i in range(len(gauss_tuples)):
    point = [((float(x)+1.0)/2.0) for x in gauss_tuples[i][0:len(gauss_tuples[i])-1]]
    weight = gauss_tuples[i][-1]
    coeff_array.append(float(weight * nodal_functions[j](*point)))
  return coeff_array

"""Core FEM Assembly"""

def generate_function_operator_lcu_diag(G, numel, numnp, numnp_bits_1D, d, j, nodal_functions, function):
  plain_tuples = generate_gauss_tuples_plain(G, numel, d)
  c_j_array = generate_c_j_array(j, nodal_functions, plain_tuples)
  print(c_j_array)
  function_operators = []
  for x_l in plain_tuples:
    commuting_operators = []
    for i in range(d):
      # XG,(i)ℓi
      commuting_operators.append(gauss_point_ith_coordinate(x_l[i], numel, numnp_bits_1D, d, i))
    function_operators.append(MQET(commuting_operators, 3, d-1,function, function.gens))
  return LinearCombination(block_encodings = tuple(function_operators), lambd = tuple(c_j_array), lambd_bits = 2)

def generate_function_operator_lcu_array(G, numel, numnp, numnp_bits_1D, d, j, k, nodal_basis_map, function):
  plain_tuples = generate_gauss_tuples_plain(G, numel, d)
  c_jk_array = generate_c_jk_array(j,k, nodal_basis_map, plain_tuples)
  print(c_jk_array)
  function_operators = []
  for x_l in plain_tuples:
    commuting_operators = []
    for i in range(d):
      # XG,(i)ℓi
      commuting_operators.append(gauss_point_ith_coordinate(x_l[i], numel, numnp_bits_1D, d, i))
    function_operators.append(MQET(commuting_operators, 3, d-1,function, function.gens))
  return LinearCombination(block_encodings = tuple(function_operators), lambd = tuple(c_jk_array), lambd_bits = 2)

class edited_product(BlockEncoding):
  def __init__(self, block_encodings):
    self.block_encodings = block_encodings
    self.s = max([block_encoding.system_bitsize for block_encoding in self.block_encodings])
    self.a = max([block_encoding.ancilla_bitsize for block_encoding in self.block_encodings])
    self.r = max([block_encoding.resource_bitsize for block_encoding in self.block_encodings])
  @property
  def signature(self):
    return Signature([Register("system", QAny(self.s)), Register("ancilla", QAny(self.a)), Register("resource", QAny(self.r))])
  @property
  def alpha(self):
    return np.prod([be.alpha for be in self.block_encodings])
  @property
  def ancilla_bitsize(self):
    return self.a
  @property
  def epsilon(self):
    first_term = self.alpha
    second_term = np.prod([be.alpha+be.epsilon for be in self.block_encodings])
    return second_term - first_term
  @property
  def system_bitsize(self):
    return self.s
  @property
  def resource_bitsize(self):
    return self.r
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([self.a]))
  def build_composite_bloq(self, bb, *, system, ancilla, resource):
    for be in self.block_encodings[::-1]:
      if be.ancilla_bitsize == 0 and be.resource_bitsize == 0:
        system = bb.add(be, system = system)
      elif be.resource_bitsize == 0:
        ancilla_bits = bb.split(ancilla)
        ancilla_used = bb.join(ancilla_bits[0:be.ancilla_bitsize])
        system, ancilla_used = bb.add(be, system = system, ancilla = ancilla_used)
        ancilla_bits_used = bb.split(ancilla_used)
        ancilla = bb.join([*ancilla_bits_used, *ancilla_bits[be.ancilla_bitsize:]])
      else:
        ancilla_bits = bb.split(ancilla)
        resource_bits = bb.split(resource)
        ancilla_used = bb.join(ancilla_bits[0:be.ancilla_bitsize])
        resource_used = bb.join(resource_bits[0:be.resource_bitsize])
        system, ancilla_used, resource_used = bb.add(be, system = system, ancilla = ancilla_used, resource = resource_used)
        ancilla_bits_used = bb.split(ancilla_used)
        resource_bits_used = bb.split(resource_used)
        ancilla = bb.join([*ancilla_bits_used, *ancilla_bits[be.ancilla_bitsize:]])
        resource = bb.join([*resource_bits_used,*resource_bits[be.resource_bitsize:]])
    return {"system": system, "ancilla": ancilla, "resource": resource}

def construct_finite_element_array(G, nen_1D, numel, numnp, numnp_bits_1D, d, nodal_basis_map, f):
  block_encodings = []
  tensored_basis = cartproduct(range(nen_1D), repeat = d)
  for j,k in cartproduct(tensored_basis, repeat = 2):
    a_j = a_j_be(numnp_bits_1D, nen_1D, numel, j, d)
    a_k_adj = AdjointBlockEncoding(a_j_be(numnp_bits_1D, nen_1D, numel, k, d))
    sum_functions = generate_function_operator_lcu_array(G, numel, numnp, numnp_bits_1D, d, j, k, nodal_basis_map, f)
    block_encodings.append(edited_product((a_j, sum_functions, a_k_adj)))
  coeffs = [1.0 for _ in range(len(block_encodings))]
  return LinearCombination(block_encodings = block_encodings, lambd = tuple(coeffs), lambd_bits = 1)

def construct_source_vector_diag(G, nen_1D, numel, numnp, numnp_bits_1D, d, nodal_basis_functions, source_function):
  block_encodings = []
  tensored_basis = cartproduct(range(nen_1D), repeat = d)
  for j in tensored_basis:
    a_j = a_j_be(numnp_bits_1D, nen_1D, numel, j, d)
    sum_functions = generate_function_operator_lcu_diag(G, numel, numnp, numnp_bits_1D, d, j, nodal_basis_functions, source_function)
    block_encodings.append(edited_product((a_j, sum_functions, AdjointBlockEncoding(a_j))))
  coeffs = [1.0 for _ in range(len(block_encodings))]
  return LinearCombination(block_encodings = block_encodings, lambd = tuple(coeffs), lambd_bits = 1)

def construct_cec_fem_matrix(numnp_bits_1D, nen_1D, numel, d, fem_coeffs):
    coeffs = []
    bes = []
    tensored_basis = cartproduct(range(nen_1D), repeat = d)
    for j,k in cartproduct(tensored_basis, repeat = 2):
        if fem_coeffs[(j,k)] != 0:
            coeffs.append(fem_coeffs[(j,k)])
            a_j = a_j_be(numnp_bits_1D, nen_1D, numel, j, d)
            a_k = a_j_be(numnp_bits_1D, nen_1D, numel, k, d)
            bes.append(unit_products(block_encodings = (a_j, AdjointBlockEncoding(a_k))))
    return LinearCombination(block_encodings = tuple(bes), lambd = tuple(coeffs), lambd_bits = 1)

def construct_cec_fem_diag(numnp_bits_1D, nen_1D, numel_1D, d, f_el):
    coeffs = []
    bes = []
    tensored_basis = cartproduct(range(nen_1D), repeat = d)
    for j in tensored_basis:
        if f_el[j] != 0:
            coeffs.append(f_el[j])
            a_j = a_j_be(numnp_bits_1D, nen_1D, numel_1D, j, d)
            bes.append(unit_products(block_encodings = (a_j, AdjointBlockEncoding(a_j))))
    return LinearCombination(block_encodings = tuple(bes), lambd = tuple(coeffs), lambd_bits = 1)
    

class u_b_1d(BlockEncoding):
  def __init__(self, numnp_bits_1D):
    self.numnp_bits_1D = numnp_bits_1D
  @property
  def signature(self):
    return Signature([Register("system",QAny(self.numnp_bits_1D)),Register("ancilla",QBit())])
  @property
  def alpha(self):
    return 1
  @property
  def ancilla_bitsize(self):
    return 1
  @property
  def epsilon(self):
    return 0
  @property
  def resource_bitsize(self):
    return 0
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([1]))
  @property
  def system_bitsize(self):
    return self.numnp_bits_1D
  def build_composite_bloq(self,bb, *, system, ancilla):
    equals_zero = EqualsAConstant(bitsize = self.numnp_bits_1D, val = 0)
    equals_edge = EqualsAConstant(bitsize = self.numnp_bits_1D, val = 2 ** self.numnp_bits_1D - 1)
    system, ancilla = bb.add(equals_zero, x = system, target = ancilla)
    system, ancilla = bb.add(equals_edge, x = system, target = ancilla)
    return {"system": system, "ancilla": ancilla}

class u_b(BlockEncoding):
  def __init__(self, numnp_bits_1D, d):
    self.numnp_bits_1D = numnp_bits_1D
    self.d = d
    encodings = [u_b_1d(numnp_bits_1D) for _ in range(self.d)]
    self.operation = TensorProduct(block_encodings = tuple(encodings))
  @property
  def signature(self):
    return self.operation.signature
  @property
  def alpha(self):
    return self.operation.alpha
  @property
  def ancilla_bitsize(self):
    return self.operation.ancilla_bitsize
  @property
  def epsilon(self):
    return self.operation.epsilon
  @property
  def resource_bitsize(self):
    return self.operation.resource_bitsize
  @property
  def signal_state(self):
    return self.operation.signal_state
  @property
  def system_bitsize(self):
    return self.operation.system_bitsize
  def build_composite_bloq(self,bb, *, system, ancilla):
    system, ancilla = bb.add(self.operation, system = system, ancilla = ancilla)
    return {"system": system, "ancilla": ancilla}

class mod_shift(Bloq):
  def __init__(self, n_bits):
    self.n_bits = n_bits
  @property
  def signature(self):
    return Signature([Register("system",QAny(self.n_bits))])
  def build_composite_bloq(self,bb, *, system):
    op = AddK(dtype = QUInt(self.n_bits), k = 1)
    system = bb.add(op, x = system)
    return {"system": system}

class base_interaction(Bloq):
  def __init__(self, n_bits):
    self.n_bits = n_bits
  @property
  def signature(self):
    return Signature([Register("system", QAny(self.n_bits)), Register("ancilla", QAny(1))])
  def build_composite_bloq(self, bb, *, system, ancilla):
    controlled_not = XGate().controlled(CtrlSpec(cvs = 2**self.n_bits - 1, qdtypes = QAny(self.n_bits)))
    system, ancilla = bb.add(controlled_not, ctrl = system, q = ancilla)
    return {"system": system , "ancilla": ancilla}
   
class unit_interaction(BlockEncoding):
  def __init__(self, numnp_bits_1D, j, k):
    self.j = j
    self.k = k
    self.numnp_bits_1D = numnp_bits_1D
    self.shift_right = mod_shift(numnp_bits_1D)
    self.shift_left = mod_shift(numnp_bits_1D).adjoint()
    self.a_zero_zero = base_interaction(numnp_bits_1D)
  @property
  def signature(self):
    return Signature([Register("system", QAny(self.numnp_bits_1D)), Register("ancilla", QAny(1))])
  @property
  def alpha(self):
    return 1
  @property
  def ancilla_bitsize(self):
    return 1
  @property
  def epsilon(self):
    return 0
  @property
  def resource_bitsize(self):
    return 0
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([1]))
  @property
  def system_bitsize(self):
    return self.numnp_bits_1D
  def build_composite_bloq(self, bb, *, system, ancilla):
    if self.j == 0 and self.k == 0:
      system, ancilla = bb.add(self.a_zero_zero, system = system, ancilla = ancilla)
    elif self.j == 0 and self.k == 1:
      system = bb.add(self.shift_left, system = system)
      system, ancilla = bb.add(self.a_zero_zero, system = system, ancilla = ancilla)
    elif self.j == 1 and self.k == 0:
      system, ancilla = bb.add(self.a_zero_zero, system = system, ancilla = ancilla)
      system = bb.add(self.shift_right, system = system)
    elif self.j == 1 and self.k == 1:
      system = bb.add(self.shift_left, system = system)
      system, ancilla = bb.add(self.a_zero_zero, system = system, ancilla = ancilla)
      system = bb.add(self.shift_right, system = system)
    return {"system": system, "ancilla": ancilla}
      
class CustomPrepare(PrepareOracle):
  def __init__(self, coeffs, phase_bitsize):
    coeffs = np.array(coeffs)
    self.coeffs = coeffs / np.linalg.norm(coeffs)
    self.phase_bitsize = phase_bitsize
    self.system_bitsize = math.ceil(math.log(len(coeffs),2))
  @property
  def selection_registers(self):
    return  [Register("selection", QAny(self.system_bitsize)),]
  @property
  def junk_registers(self):
    return []
  @property
  def signature(self):
    return Signature(self.selection_registers)
  def build_composite_bloq(self, bb, *, selection):
    prepare_b = StatePreparationViaRotations(phase_bitsize = self.phase_bitsize, state_coefficients = tuple(self.coeffs))
    phase_gradient = bb.add(PhaseGradientState(self.phase_bitsize))
    selection, phase_gradient = bb.add(prepare_b, target_state = selection, phase_gradient = phase_gradient)
    bb.add(PhaseGradientState(bitsize=self.phase_bitsize).adjoint(), phase_grad=phase_gradient)
    return {"selection": selection}

def construct_cec_fem_matrix_special_1D(numnp_bits_1D, fem_coeffs):
    coeffs = []
    bes = []
    for j,k in cartproduct(range(2), repeat = 2):
        j = (j,)
        k = (k,)
        if fem_coeffs[(j,k)] != 0:
            coeffs.append(fem_coeffs[(j,k)])
            bes.append(unit_interaction(numnp_bits_1D, j[0], k[0]))
    prep_coeffs = np.sqrt([abs(coeffs[i]) * bes[i].alpha for i in range(len(bes))])
    return LinearCombination(block_encodings = tuple(bes), lambd = tuple(coeffs), lambd_bits = 1, prepare = CustomPrepare(prep_coeffs, 3))

def construct_cec_fem_diag_special_1D(numnp_bits_1D, f_el):
    coeffs = []
    bes = []
    for j in range(2):
        j = (j,)
        if f_el[j] != 0:
            coeffs.append(f_el[j])
            bes.append(unit_interaction(numnp_bits_1D, j[0], j[0]))
    prep_coeffs = np.sqrt([abs(coeffs[i]) * bes[i].alpha for i in range(len(bes))])
    return LinearCombination(block_encodings = tuple(bes), lambd = tuple(coeffs), lambd_bits = 1, prepare = CustomPrepare(prep_coeffs, 3))

def construct_full_l_1D(numnp_bits_1D, k_el, m_el):
    coeffs = []
    bes = []
    for j,k in cartproduct(range(2), repeat = 2):
        j = (j,)
        k = (k,)
        coeffs.append(k_el[(j,k)]+m_el[(j,k)])
        bes.append(unit_interaction(numnp_bits_1D, j[0], k[0]))
    prep_coeffs = np.sqrt([abs(coeffs[i]) * bes[i].alpha for i in range(len(bes))])
    return LinearCombination(block_encodings = tuple(bes), lambd = tuple(coeffs), lambd_bits = 1, prepare = CustomPrepare(prep_coeffs, 3))
