# -*- coding: utf-8 -*-
"""QuFEM_in_Qualtran.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d1-BRF9ILXUjYE62_qy0TQEfmZxzWQa3

Imports
"""

from itertools import product as cartproduct
import math
import random
from typing import *
import qu_fem_in_qualtran
from qu_fem_in_qualtran.mqet import MQET
from qu_fem_in_qualtran.quantum_linear_systems import qlsp_solver_prepared
from qu_fem_in_qualtran.quantum_linear_systems import prep_vector
from qualtran.bloqs.mod_arithmetic import *
import cirq
import numpy as np
import pennylane as qml
import pyqsp
import qualtran
import qualtran.simulation as sim
import sympy
from numpy.polynomial import Chebyshev
from qualtran.bloqs.bookkeeping import Partition
from scipy.linalg import sqrtm
from qualtran import (
    Bloq,
    BloqBuilder,
    CompositeBloq,
    CtrlSpec,
    QAny,
    QBit,
    QInt,
    QUInt,
    Register,
    Signature,
    cirq_interop,
)
from sympy import legendre
from qualtran.bloqs import *
from qualtran.bloqs.arithmetic import *
from qualtran.bloqs.arithmetic.permutation import Permutation
from qualtran.bloqs.basic_gates import (
    CNOT,
    GlobalPhase,
    Hadamard,
    IntEffect,
    OneEffect,
    OneState,
    PlusState,
    Rz,
    SGate,
    Swap,
    TGate,
    XGate,
    ZeroState,
    ZGate,
)
from qualtran.bloqs.basic_gates import Identity
from qualtran.bloqs.block_encoding import (
    BlockEncoding,
    LinearCombination,
    Product as BlockEncodingProduct,
    TensorProduct,
    Unitary,
)
from qualtran.bloqs.data_loading.qrom import QROM
from qualtran.bloqs.qsp.generalized_qsp import GeneralizedQSP
from qualtran.bloqs.reflections.prepare_identity import PrepareIdentity
from qualtran.bloqs.rotations.phase_gradient import PhaseGradientState
from qualtran.bloqs.state_preparation.black_box_prepare import BlackBoxPrepare
from qualtran.bloqs.state_preparation.state_preparation_via_rotation import (
    StatePreparationViaRotations,
)
from itertools import combinations
from qualtran.cirq_interop import CirqGateAsBloq
from qualtran.drawing import (
    show_bloq,
    show_call_graph,
    show_counts_sigma,
)
from qualtran.bloqs.state_preparation import PrepareUniformSuperposition
from sympy import diff
import sympy as sp
from sympy import degree
from qualtran.bloqs.arithmetic import EqualsAConstant

"""Adjoint BE Wrapper"""

class AdjointBlockEncoding(BlockEncoding):
  def __init__(self,block_encoding):
    self.block_encoding = block_encoding
  @property
  def signature(self):
    return self.block_encoding.signature
  @property
  def alpha(self):
    return self.block_encoding.alpha
  @property
  def ancilla_bitsize(self):
    return self.block_encoding.ancilla_bitsize
  @property
  def epsilon(self):
    return self.block_encoding.epsilon
  @property
  def resource_bitsize(self):
    return self.block_encoding.resource_bitsize
  @property
  def signal_state(self):
    return self.block_encoding.signal_state
  @property
  def system_bitsize(self):
    return self.block_encoding.system_bitsize
  def build_composite_bloq(self, bb, system, ancilla):
    system, ancilla = bb.add(self.block_encoding.adjoint(),system = system, ancilla = ancilla)
    return {"system": system, "ancilla": ancilla}

"""Position Operators/Q"""

class z_i(Bloq):
  def __init__(self, n, i):
    self.n = n
    self.i = i
  @property
  def signature(self):
    return Signature([Register("point",QAny(self.n))])
  def build_composite_bloq(self, bb, *, point):
    point_array = bb.split(point)
    point_array[self.n - self.i -1] = bb.add(ZGate(),q = point_array[self. n - self.i -1])
    point = bb.join(point_array, dtype = QAny(self.n))
    return {"point": point}

def build_x(n):
  N = 2**n
  coeffs = [(N-1)/2]
  unitaries = [Unitary(Identity(n))]
  for i in range(n):
    coeffs.append(-(0.5 * (2**i)))
    unitaries.append(Unitary(z_i(n,i)))
  return LinearCombination(tuple(unitaries),lambd = tuple(coeffs), lambd_bits = 3)

"""Mesh Connectivity Block Encoding"""

class o_l_numel(Bloq):
  def __init__(self, numel, numel_bits):
    self.numel = numel
    self.numel_bits = numel_bits
  @property
  def signature(self):
    return Signature([Register("el", QUInt(self.numel_bits)),Register("flag", QBit())])
  def build_composite_bloq(self, bb, *, el, flag):
    numel_reg = bb.allocate(dtype = QUInt(self.numel_bits))
    numel_reg_bits = bb.split(numel_reg)
    for index in range(self.numel_bits):
      if (self.numel >> index) & 1:
        numel_reg_bits[self.numel_bits - index - 1] = bb.add(XGate(), q = numel_reg_bits[self.numel_bits - index - 1])
    numel_reg = bb.join(numel_reg_bits, dtype = QUInt(self.numel_bits))
    numel_reg, el , flag = bb.add(GreaterThan(a_bitsize = self.numel_bits, b_bitsize = self.numel_bits), a = numel_reg, b = el, target = flag)
    numel_reg_bits = bb.split(numel_reg)
    for index in range(self.numel_bits):
      if (self.numel >> index) & 1:
        numel_reg_bits[self.numel_bits - index - 1] = bb.add(XGate(), q = numel_reg_bits[self.numel_bits - index - 1])
    numel_reg = bb.join(numel_reg_bits)
    bb.free(numel_reg)
    return {"el": el, "flag": flag}

class O_IX_1D(Bloq):
  def __init__(self, numnp_bits, nen, numel, j):
    self.nen = nen
    self.numnp_bits = numnp_bits
    self.j = j
    map = []
    inverse_map = [0 for _ in range(2 ** numnp_bits)]
    for el in range(numel):
      op = (el * (nen - 1) + j) % (2 ** self.numnp_bits)
      map.append(op)
      inverse_map[op] = el
    map = np.array(map)
    inverse_map = np.array(inverse_map)
    self.map = QROM((map,), (self.numnp_bits,), (self.numnp_bits,))
    self.inv = QROM((inverse_map,), (self.numnp_bits,), (self.numnp_bits,))
  @property
  def signature(self):
    return Signature([Register("system", QAny(self.numnp_bits))])
  def build_composite_bloq(self, bb, *, system):
    ret_val = bb.allocate(self.numnp_bits)
    system, ret_val = bb.add(self.map, selection = system, target0_ = ret_val)
    ret_val, system = bb.add(self.inv, selection = ret_val, target0_ = system)
    bb.free(system)
    return {"system": ret_val}

class a_j_block_encoding_1D(BlockEncoding):
  def __init__(self,numnp_bits, nen, numel, j):
    self.oracle_ix = O_IX_1D(numnp_bits, nen, numel, j)
    self.oracle_l_numel = o_l_numel(numel, numnp_bits)
    self.numnp_bits = numnp_bits
    self.j = j
  @property
  def signature(self):
    return Signature([Register("system", QUInt(self.numnp_bits)),Register("ancilla", QAny(1))])
  @property
  def alpha(self):
    return 1
  @property
  def ancilla_bitsize(self):
    return 1
  @property
  def epsilon(self):
    return 0
  @property
  def resource_bitsize(self):
    return 0
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([1]))
  @property
  def system_bitsize(self):
    return self.numnp_bits
  def build_composite_bloq(self,bb, *, system, ancilla):
    system, ancilla = bb.add(self.oracle_l_numel, el = system, flag = ancilla)
    system = bb.add(self.oracle_ix, system = system)
    ancilla = bb.add(XGate(), q= ancilla)
    return {"system": system, "ancilla": ancilla}

class a_j_be(BlockEncoding):
  def __init__(self,numnp_bits, nen_1D, numel, j, d):
    self.one_dimensional_bes = [a_j_block_encoding_1D(numnp_bits, nen_1D,numel, j[i]) for i in range(d)]
    self.operation = TensorProduct(block_encodings = tuple(self.one_dimensional_bes))
  @property
  def signature(self):
    return self.operation.signature
  @property
  def alpha(self):
    return self.operation.alpha
  @property
  def ancilla_bitsize(self):
    return self.operation.ancilla_bitsize
  @property
  def epsilon(self):
    return self.operation.epsilon
  @property
  def resource_bitsize(self):
    return self.operation.resource_bitsize
  @property
  def signal_state(self):
    return self.operation.signal_state
  @property
  def system_bitsize(self):
    return self.operation.system_bitsize
  def build_composite_bloq(self, bb, *, system, ancilla):
    system, ancilla = bb.add(self.operation, system = system, ancilla = ancilla)
    return {"system": system, "ancilla": ancilla}

"""Quadrature Point Position Operators"""

class log_numel_projector(BlockEncoding):
  def __init__(self, numnp_bits, numel):
    self.numnp_bits = numnp_bits
    self.numel = numel
  @property
  def signature(self):
    return Signature([Register("system",QAny(self.numnp_bits)),Register("ancilla",QBit())])
  @property
  def alpha(self):
    return 1
  @property
  def ancilla_bitsize(self):
    return 1
  @property
  def epsilon(self):
    return 0
  @property
  def resource_bitsize(self):
    return 0
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([1]))
  @property
  def system_bitsize(self):
    return self.numnp_bits
  def build_composite_bloq(self,bb, *, system, ancilla):
    numel_reg = bb.allocate(dtype = QUInt(self.numnp_bits))
    numel_reg_bits = bb.split(numel_reg)
    for index in range(self.numnp_bits):
      if (self.numel >> index) & 1:
        numel_reg_bits[self.numnp_bits - index - 1] = bb.add(XGate(), q = numel_reg_bits[self.numnp_bits - index - 1])
    numel_reg = bb.join(numel_reg_bits, dtype = QUInt(self.numnp_bits))
    numel_reg, system , ancilla = bb.add(GreaterThan(a_bitsize = self.numnp_bits, b_bitsize = self.numnp_bits), a = numel_reg, b = system, target = ancilla)
    numel_reg_bits = bb.split(numel_reg)
    for index in range(self.numnp_bits):
      if (self.numel >> index) & 1:
        numel_reg_bits[self.numnp_bits - index - 1] = bb.add(XGate(), q = numel_reg_bits[self.numnp_bits - index - 1])
    numel_reg = bb.join(numel_reg_bits)
    ancilla = bb.add(XGate(),q = ancilla)
    bb.free(numel_reg)
    return {"system": system, "ancilla": ancilla}
def generate_x_l_i_el(x_l_i, numel, n_bits, d):
  h = 1/numel
  coeff_1 = h * (x_l_i+ 1)/2
  coeff_2 = h
  inner = LinearCombination(block_encodings = (Unitary(Identity(n_bits)), build_x(n_bits)), lambd = (coeff_1,coeff_2),lambd_bits = 4)
  return BlockEncodingProduct((log_numel_projector(n_bits,numel), inner))
# ith coordinate of the lth gauss point for a certain element varies between elements
class gauss_point_ith_coordinate(BlockEncoding):
  def __init__(self, x_l_i, numel, n_bits, d, i):
    encodings = [log_numel_projector(numel = numel,numnp_bits = n_bits)] * d
    encodings[d - i - 1] = generate_x_l_i_el(x_l_i = x_l_i, numel = numel, n_bits = n_bits, d = d)
    self.operation = TensorProduct(block_encodings = tuple(encodings))
  @property
  def signature(self):
    return self.operation.signature
  @property
  def alpha(self):
    return self.operation.alpha
  @property
  def ancilla_bitsize(self):
    return self.operation.ancilla_bitsize
  @property
  def epsilon(self):
    return self.operation.epsilon
  @property
  def resource_bitsize(self):
    return self.operation.resource_bitsize
  @property
  def signal_state(self):
    return self.operation.signal_state
  @property
  def system_bitsize(self):
    return self.operation.system_bitsize
  def build_composite_bloq(self, bb, *, system, ancilla, resource):
    system, ancilla, resource = bb.add(self.operation, system = system, ancilla = ancilla, resource = resource)
    return {"system": system, "ancilla": ancilla, "resource":resource}

"""Gauss Tuples and Quadrature Coefficients"""

def generate_gauss_tuples_plain(G, numel, d):
  one_dimensional_points = []
  x = sp.symbols("x")
  poly = sp.Poly(legendre(G,x))
  poly_deriv = diff(poly, x)
  for x_k in poly.nroots():
    one_dimensional_points.append(x_k)
  return list(cartproduct(one_dimensional_points, repeat = d))

def generate_gauss_tuples_1D(G, numel, el, d):
  gauss_tuples = []
  x = sp.symbols("x")
  poly = sp.Poly(legendre(G,x))
  poly_deriv = diff(poly, x)
  h = 1/(numel)
  for x_k in poly.nroots():
    w_k = 2 / (((1 - x_k**2))*(poly_deriv(x_k)**2))
    x_k_el = h* (x_k + 1)/2 + h*el
    w_k_el = (h/2)*w_k
    gauss_tuples.append((w_k_el, x_k_el))
  return gauss_tuples

def generate_gauss_tuples(G, numel, d):
  one_dimensional_points = generate_gauss_tuples_1D(G, numel, el, d)
  higher_d_tuples = []
  for tup in cartproduct(one_dimensional_points, repeat = d):
    whole = []
    weight = 1
    for index in tup:
      whole.append(index[1])
      weight = weight * index[0]
    whole.append(weight)
    higher_d_tuples.append(tuple(whole))
  return higher_d_tuples

def generate_c_jk_array(j,k, nodal_basis_map, gauss_tuples):
  coeff_array = []
  for i in range(len(gauss_tuples)):
    point = list(gauss_tuples[i][0:len(gauss_tuples[i])-1])
    weight = gauss_tuples[i][-1]
    coeff_array.append(weight * nodal_basis_map[(j,k)](*point))
  return coeff_array

def generate_c_j_array(j, nodal_functions, gauss_tuples):
  coeff_array = []
  for i in range(len(gauss_tuples)):
    point = list(gauss_tuples[i][0:len(gauss_tuples[i])-1])
    weight = gauss_tuples[i][-1]
    coeff_array.append(weight * nodal_functions[j](*point))
  return coeff_array

"""Function Operator LCU"""

def generate_function_operator_lcu_diag(G, nen, numel, numnp, numnp_bits, d, j, nodal_functions, function):
  tuples = generate_gauss_tuples_plain(G, numel, d)
  c_j_array = generate_c_j_array(j, nodal_functions, tuples)
  function_operators = []
  for x_l in tuples:
    commuting_operators = []
    for i in range(d):
      # XG,(i)ℓi
      commuting_operators.append(gauss_point_ith_coordinate(x_l[i], numel, numnp_bits, d, i))
    function_operators.append(MQET(commuting_operators, 5, d,function, function.gens))
  return LinearCombination(block_encodings = tuple(function_operators), lambd = tuple(c_j_array), lambd_bits = 5)

def generate_function_operator_lcu_array(G, numel, numnp, numnp_bits, d, j, k, nodal_basis_map, function):
  tuples = generate_gauss_tuples_plain(G, numel, d)
  c_jk_array = generate_c_jk_array(j,k, nodal_basis_map, tuples)
  function_operators = []
  for x_l in tuples:
    commuting_operators = []
    for i in range(d):
      # XG,(i)ℓi
      commuting_operators.append(gauss_point_ith_coordinate(x_l[i], numel, numnp_bits, d, i))
    function_operators.append(MQET(commuting_operators, 5, d,function, function.gens))
  return LinearCombination(block_encodings = tuple(function_operators), lambd = tuple(c_jk_array), lambd_bits = 5)

"""Finite Element Arrays/Vectors Assembly"""

def construct_finite_element_array(G, nen_1D, numel, numnp, numnp_bits, d, nodal_basis_map, f):
  block_encodings = []
  tensored_basis = cartproduct(range(nen_1D), repeat = d)
  for j,k in cartproduct(tensored_basis, repeat = 2):
    a_j = a_j_be(numnp_bits, nen_1D, numel, j, d)
    a_k_adj = AdjointBlockEncoding(a_j_be(numnp_bits, nen_1D, numel, k, d))
    sum_functions = generate_function_operator_lcu_array(G, numel, numnp, numnp_bits, d, j, k, nodal_basis_map, f)
    block_encodings.append(BlockEncodingProduct((a_j, sum_functions, a_k_adj)))
  coeffs = [1.0 for _ in range(len(block_encodings))]
  return LinearCombination(block_encodings = tuple(block_encodings),lambd = tuple(coeffs),lambd_bits = 5)

def construct_source_vector_diag(G, nen_1D, numel, numnp, numnp_bits, d, nodal_basis_functions, source_function):
  block_encodings = []
  tensored_basis = cartproduct(range(nen_1D), repeat = d)
  for j,k in cartproduct(tensored_basis, repeat = 2):
    a_j = a_j_be(numnp_bits, nen_1D, numel, j, d)
    sum_functions = generate_function_operator_lcu_diag(G, numel, numnp, numnp_bits, d, j, nodal_basis_functions, source_function)
    block_encodings.append(BlockEncodingProduct((a_j_be, sum_functions, AdjointBlockEncoding(a_j))))
  coeffs = [1.0 for _ in range(len(block_encodings))]
  return LinearCombination(block_encodings = tuple(block_encodings),lambd = tuple(coeffs),lambd_bits = 5)

"""Boundary Conditions Operators"""

class u_b_1d(BlockEncoding):
  def __init__(self, numnp_bits):
    self.numnp_bits = numnp_bits
  @property
  def signature(self):
    return Signature([Register("system",QAny(self.numnp_bits)),Register("ancilla",QBit())])
  @property
  def alpha(self):
    return 1
  @property
  def ancilla_bitsize(self):
    return 1
  @property
  def epsilon(self):
    return 0
  @property
  def resource_bitsize(self):
    return 0
  @property
  def signal_state(self):
    return BlackBoxPrepare(prepare = PrepareIdentity.from_bitsizes([1]))
  @property
  def system_bitsize(self):
    return self.numnp_bits
  def build_composite_bloq(self,bb, *, system, ancilla):
    equals_zero = EqualsAConstant(bitsize = self.numnp_bits, val = 0)
    equals_edge = EqualsAConstant(bitsize = self.numnp_bits, val = 2 ** self.numnp_bits - 1)
    system, ancilla = bb.add(equals_zero, x = system, target = ancilla)
    system, ancilla = bb.add(equals_edge, x = system, target = ancilla)
    return {"system": system, "ancilla": ancilla}

class u_b(BlockEncoding):
  def __init__(self, numnp_bits, d):
    self.numnp_bits = numnp_bits
    self.d = d
    encodings = [u_b_1d(numnp_bits) for _ in range(self.d)]
    self.operation = TensorProduct(block_encodings = tuple(encodings))
  @property
  def signature(self):
    return self.operation.signature
  @property
  def alpha(self):
    return self.operation.alpha
  @property
  def ancilla_bitsize(self):
    return self.operation.ancilla_bitsize
  @property
  def epsilon(self):
    return self.operation.epsilon
  @property
  def resource_bitsize(self):
    return self.operation.resource_bitsize
  @property
  def signal_state(self):
    return self.operation.signal_state
  @property
  def system_bitsize(self):
    return self.operation.system_bitsize
  def build_composite_bloq(self,bb, *, system, ancilla):
    system, ancilla = bb.add(self.operation, system = system, ancilla = ancilla)
    return {"system": system, "ancilla": ancilla}

"""Testing"""
