# -*- coding: utf-8 -*-
"""Copy_of_quantum_linear_systems.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ofLbH6_V1CFH02HpiZOL7W0h1oNOYKPK

Installation
"""

"""Solves BE(A) @ |v>|0> = b for A< v, b, preparing a quantum state |v> that is proportional to the solution"""

"""Imports"""

import sys
sys.path.insert(0, './pyqsp')
from qualtran.bloqs.basic_gates import TGate
import math
from qualtran.bloqs.basic_gates import Rz
import random
from itertools import product
from qualtran.bloqs.basic_gates import IntState
from typing import *
import numpy as np
import sympy
import cirq
from scipy.linalg import sqrtm
from numpy.polynomial import Chebyshev
import qualtran
from qualtran.bloqs.basic_gates import SGate
from qualtran import (
    Bloq,
    BloqBuilder,
    CompositeBloq,
    Signature,
    Register,
    CtrlSpec,
    QBit,
    QInt,
    QUInt,
    QAny,
    cirq_interop,
)
import qualtran.simulation as sim
from qualtran.bloqs import *
from qualtran.bloqs.arithmetic import *
from qualtran.bloqs.basic_gates import (
    Swap,
    XGate,
    ZGate,
    Identity,
    ZeroState,
    OneState,
    OneEffect,
    PlusState,
    CNOT,
)
from qualtran.bloqs.basic_gates import IntEffect
from qualtran.bloqs.block_encoding import (
    BlockEncoding,
    Unitary,
    LinearCombination,
    TensorProduct,
    Product as BlockEncodingProduct,
)
from qualtran.bloqs.data_loading.qrom import QROM
from qualtran.bloqs.arithmetic.permutation import Permutation
from qualtran.bloqs.reflections.prepare_identity import PrepareIdentity
from qualtran.bloqs.state_preparation.black_box_prepare import BlackBoxPrepare
from qualtran.bloqs.state_preparation.state_preparation_via_rotation import (
    StatePreparationViaRotations,
)
from qualtran.bloqs.rotations.phase_gradient import PhaseGradientState
from qualtran.bloqs.qsp.generalized_qsp import GeneralizedQSP
from qualtran.drawing import (
    show_bloq,
    show_call_graph,
    show_counts_sigma,
)
from qualtran.cirq_interop import CirqGateAsBloq
import pennylane as qml
import pyqsp
from pyqsp.angle_sequence import QuantumSignalProcessingPhases
from pyqsp.poly import PolyOneOverX
from qualtran.bloqs.basic_gates import Hadamard
from qualtran.bloqs.basic_gates import GlobalPhase

"""Adjoint Block Encoding"""

class AdjointBlockEncoding(BlockEncoding):
  def __init__(self,block_encoding):
    self.block_encoding = block_encoding
  @property
  def signature(self):
    return self.block_encoding.signature
  @property
  def alpha(self):
    return self.block_encoding.alpha
  @property
  def ancilla_bitsize(self):
    return self.block_encoding.ancilla_bitsize
  @property
  def epsilon(self):
    return self.block_encoding.epsilon
  @property
  def resource_bitsize(self):
    return self.block_encoding.resource_bitsize
  @property
  def signal_state(self):
    return self.block_encoding.signal_state
  @property
  def system_bitsize(self):
    return self.block_encoding.system_bitsize
  def build_composite_bloq(self, bb, system, ancilla, resource):
    system, ancilla, resource = bb.add(self.block_encoding.adjoint(),system = system, ancilla = ancilla, resource = resource)
    return {"system": system, "ancilla": ancilla, "resource": resource}

"""QSVT Bloq"""

# Implements P(A) + iQ(A)
class QSVT(BlockEncoding):
  def __init__(self, block_encoding, angles):
    self.block_encoding = block_encoding
    self.adjoint_block_encoding = AdjointBlockEncoding(block_encoding)
    self.angles = angles
  @property
  def signature(self):
    return self.block_encoding.signature
  @property
  def alpha(self):
    return self.block_encoding.alpha
  @property
  def ancilla_bitsize(self):
    return self.block_encoding.ancilla_bitsize
  @property
  def epsilon(self):
    return self.block_encoding.epsilon
  @property
  def resource_bitsize(self):
    return self.block_encoding.resource_bitsize
  @property
  def signal_state(self):
    return self.block_encoding.signal_state
  @property
  def system_bitsize(self):
    return self.block_encoding.system_bitsize
  def build_composite_bloq(self, bb, *, system, ancilla, resource):
    bb.add(GlobalPhase(exponent = -1 * self.angles[0] / np.pi))
    ancilla = bb.add(GlobalPhase(exponent = 2* self.angles[0]/ np.pi).controlled(CtrlSpec(qdtypes = QAny(self.ancilla_bitsize), cvs = 0)), ctrl = ancilla)
    adj = False
    for angle in self.angles[1:]:
      if adj:
        system, ancilla, resource = bb.add(self.adjoint_block_encoding, system = system, ancilla = ancilla, resource = resource)
      else:
         system, ancilla, resource = bb.add(self.block_encoding, system = system, ancilla = ancilla, resource = resource)
      adj = not adj
      bb.add(GlobalPhase(exponent = -1 * angle / np.pi))
      ancilla = bb.add(GlobalPhase(exponent = 2* angle / np.pi).controlled(CtrlSpec(qdtypes = QAny(self.ancilla_bitsize), cvs = 0)), ctrl = ancilla)
    return {"system": system, "ancilla": ancilla, "resource": resource}
# Implements P(A)- iQ(A)
class QSVT_Adj_Im(BlockEncoding):
  def __init__(self, block_encoding, angles):
    self.block_encoding = block_encoding
    self.adjoint_block_encoding = AdjointBlockEncoding(block_encoding)
    self.angles = angles
  @property
  def signature(self):
    return self.block_encoding.signature
  @property
  def alpha(self):
    return self.block_encoding.alpha
  @property
  def ancilla_bitsize(self):
    return self.block_encoding.ancilla_bitsize
  @property
  def epsilon(self):
    return self.block_encoding.epsilon
  @property
  def resource_bitsize(self):
    return self.block_encoding.resource_bitsize
  @property
  def signal_state(self):
    return self.block_encoding.signal_state
  @property
  def system_bitsize(self):
    return self.block_encoding.system_bitsize
  def build_composite_bloq(self, bb, *, system, ancilla, resource):
    bb.add(GlobalPhase(exponent = 1 * self.angles[0] / np.pi))
    ancilla = bb.add(GlobalPhase(exponent = -2* self.angles[0] / np.pi).controlled(CtrlSpec(qdtypes = QAny(self.ancilla_bitsize), cvs = 0)), ctrl = ancilla)
    adj = False
    for angle in self.angles[1:]:
      if adj:
        system, ancilla, resource = bb.add(self.adjoint_block_encoding, system = system, ancilla = ancilla, resource = resource)
      else:
         system, ancilla, resource = bb.add(self.block_encoding, system = system, ancilla = ancilla, resource = resource)
      adj = not adj
      bb.add(GlobalPhase(exponent = 1 * angle / np.pi))
      ancilla = bb.add(GlobalPhase(exponent = -2* angle / np.pi).controlled(CtrlSpec(qdtypes = QAny(self.ancilla_bitsize), cvs = 0)), ctrl = ancilla)
    return {"system": system, "ancilla": ancilla, "resource": resource}

"""QSVT(Approximation of c/x on singular values)"""

def return_qsvt(M, kappa, epsilon):
  coeffs, scale = pyqsp.poly.PolyOneOverX().generate(return_scale = True, kappa = kappa, epsilon = epsilon)
  angles_qsp = pyqsp.angle_sequence.QuantumSignalProcessingPhases(coeffs, method = "laurent", signal_operator = "Wx")
  angles_qsvt = qml.transform_angles(angles_qsp, "QSP","QSVT")
  return QSVT(M, angles_qsvt)
"""def return_qsvt_op(M):
  coeffs, scale = pyqsp.poly.PolyOneOverX().generate(return_scale = True, kappa = 2, epsilon = 0.5)
  angles_qsp = pyqsp.angle_sequence.QuantumSignalProcessingPhases(coeffs)
  angles_qsvt = qml.transform_angles(angles_qsp, "QSP","QSVT")
  return QSVT_Adj_Im(M, angles_qsvt)"""

"""QLSP Solver"""

def prep_vector(bb,b, phases):
    phase_bitsize = 5
    prepare_b = StatePreparationViaRotations(phase_bitsize = phase_bitsize, state_coefficients = tuple(b))
    phase_gradient = bb.add(PhaseGradientState(phase_bitsize))
    state, phase_gradient = bb.add(prepare_b, target_state = phases, phase_gradient = phase_gradient)
    bb.add(PhaseGradientState(bitsize=phase_bitsize).adjoint(), phase_grad=phase_gradient)
    return state
# Assumes A and b are padded to a power of 2
"""def qlsp_solver(n, A, b, bb):
  # prepares b state
  system = prep_vector(bb,b,bb.allocate(int(math.log(len(b),2))))
  # prepares QSVT
  f_A = return_qsvt(A) # P(A) + iQ(A)
  f_A_Poly_Adj = return_qsvt_op(A)# P(A)-iQ(A)
  # hadamard trick for performing an LCU of these
  f_A_controlled = f_A.controlled(CtrlSpec())
  f_A_Poly_Adj= f_A_Poly_Adj.controlled(CtrlSpec())
  # Takes the adjoint operation to get BE(A^-1) with extra ancillas
  # Allocates registers for the LCU
  ctrl = bb.add(ZeroState())
  ancilla = bb.add(IntState(val = 0, bitsize = f_A.ancilla_bitsize))
  resource = bb.add(IntState(val = 0, bitsize = f_A.resource_bitsize))
  f_a_c_inv = f_A_controlled.adjoint()
  f_a_c_adj_inv = f_A_Poly_Adj.adjoint()
  # performs operation
  ctrl = bb.add(Hadamard(),q = ctrl)
  ctrl, system, ancilla, resource = bb.add(f_a_c_inv,ctrl = ctrl, system = system, ancilla = ancilla, resource = resource)
  ctrl = bb.add(XGate(), q = ctrl)
  ctrl, system, ancilla, resource = bb.add(f_a_c_adj_inv,ctrl = ctrl, system = system, ancilla = ancilla, resource = resource)
  ctrl = bb.add(Hadamard(),q = ctrl)
  # Postselects registers
  bb.add(IntEffect(0, 1), val = ctrl)
  bb.add(IntEffect(0, f_A.ancilla_bitsize), val = ancilla)
  bb.add(IntEffect(0, f_A.resource_bitsize), val = resource)
  circuit = bb.finalize(system = system)
  return circuit"""
    
def qlsp_solver_prepared(A, system, bb):
  # prepares QSVT
  f_A = return_qsvt(A) # P(A) + iQ(A)
  # Takes the adjoint operation to get BE(A^-1) with extra ancillas
  ancilla = bb.add(IntState(val = 0, bitsize = f_A.ancilla_bitsize))
  resource = bb.add(IntState(val = 0, bitsize = f_A.resource_bitsize))
  f_a_inv = f_A.adjoint()
  # performs operation
  system, ancilla, resource = bb.add(f_a_inv, system = system, ancilla = ancilla, resource = resource)
  # Postselects registers
  bb.add(IntEffect(0, f_A.ancilla_bitsize), val = ancilla)
  bb.add(IntEffect(0, f_A.resource_bitsize), val = resource)
  circuit = bb.finalize(system = system)
  return circuit

"""Testing

A = LinearCombination(block_encodings = (Unitary(Identity()),Unitary(SGate()),Unitary(TGate()),Unitary(ZGate()) ), lambd = (1.0,1.0, 1.0,1.0), lambd_bits = 1)
b = np.array([1,1])/ np.sqrt(2)
n = 2
bb = BloqBuilder()
sol1 = qlsp_solver(n,A,b,bb).tensor_contract()
Identit = np.array([[1,0],[0,1]], dtype = complex)
SGat = np.array([[1,0],[0,1j]], dtype = complex)
TGat = np.array([[1,0],[0,math.e ** (1j*math.pi/4)]], dtype = complex)
ZGat =np.array([[1,0],[0,-1]], dtype = complex)
comb = Identit + SGat + TGat + ZGat
print(sol1 / np.linalg.norm(sol1, 1))
print(np.linalg.inv(comb) @ b / np.linalg.norm((np.linalg.inv(comb) @ b ), 1))
v1 = sol1 / np.linalg.norm(sol1)
v2 = np.linalg.inv(comb) @ b / np.linalg.norm((np.linalg.inv(comb) @ b ))
print(np.vdot(v1,v2))
"""
